language: r
#sudo: false
script: make ts_explore
cache: 
  packages: true
warnings_are_errors: false
jobs:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
addons:
  apt:
    packages: cabal-install
  homebrew: 
    packages: pandoc-crossref
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cabal update && 
    cabal install pandoc-crossref; fi
